services:
  web:
    image: nginx:1.29-alpine
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  slow-broken:
    image: python:3.14-alpine
    command: >
      sh -c "
        echo 'Starting slow service...';
        sleep 10;
        python -m http.server 8080
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 0s
