name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup jq
        uses: dcarbone/install-jq-action@v3

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"

      - name: Run BATS (pretty + JUnit report)
        shell: bash
        env:
          BATS_LIB_PATH: "${{ steps.setup-bats.outputs.lib-path }}"
          TERM: xterm
        run: |
          mkdir -p test-reports
          bats \
          --formatter tap \
          --print-output-on-failure \
          --report-formatter junit \
          --output test-reports \
          tests/

      - name: Upload JUnit report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: junit-report
          path: test-reports/**/*.xml
