name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup jq
        uses: dcarbone/install-jq-action@v3

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1
        with:
          support-path: "${{ github.workspace }}/.bats/bats-support"
          assert-path: "${{ github.workspace }}/.bats/bats-assert"
          detik-path: "${{ github.workspace }}/.bats/bats-detik"
          file-path: "${{ github.workspace }}/.bats/bats-file"

      - name: Run BATS (pretty + JUnit report)
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
        run: |
          set -euo pipefail
          echo "BATS_LIB_PATH=$BATS_LIB_PATH"
          echo "which bats: $(which bats)"
          bats --version || true

          echo "== check bats-support exists in BATS_LIB_PATH =="
          find "$BATS_LIB_PATH" -maxdepth 4 -type f -name "load.bash" -o -name "load" || true

          mkdir -p test-reports
          bats \
          --formatter tap \
          --print-output-on-failure \
          --report-formatter junit \
          --output test-reports \
          tests/

      - name: Upload JUnit report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: junit-report
          path: test-reports/**/*.xml
