name: "Workflow when docker compose failed"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-health-when-no-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Docker Compose health check (EXPECTED -> COMPOSE FAILED)
        id: healthcheck
        uses: ./
        continue-on-error: true
        with:
          compose-files: |
            docker-compose-NOT-FOUND.yml
          services: "empty"
          timeout: "10"
          additional-compose-args: ""

      - name: Assert that workflow failed due to no services and diagnostics are correct
        if: always()
        run: |
          OUTPUT="$(echo "${{ steps.healthcheck.outputs.summary_b64 }}" | base64 -d)"

          assert() {
            local regex="$1"
            if ! echo "$OUTPUT" | grep -Eq "$regex"; then
              echo "❌ Expected to match: $regex"
              echo "   Regex: $regex"
              exit 1
            fi
          }

          assert 'Diagnostics summary'
          assert '^  Platform:[[:space:]].+'
          assert '^  Global timeout:[[:space:]]*10s \(per service\)$'
          assert 'docker-compose-NOT-FOUND\.yml'
          assert 'docker compose output \(last 25 lines\)'
          assert 'docker compose ls \(all projects\)'
          assert 'docker ps --all \(global\)'
          assert 'no such file or directory'

          echo "✅ Compose fail diagnostics validated successfully."
